# Generated by Django 4.2.20 on 2025-03-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='nombre_cabines',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
